# Docker-Compose for CTF
version: '3'
services:
  mazeoffiles: 
    build: ./containers/MazeOfFiles
    ports:
      - "2222:22" # Port 22 du container est exposé sur le port 2223 de la machine hôte
    container_name: mazeoffiles
    tty: true
    stdin_open: true
    restart: always
    networks:
      - ctf

  junksoup:
    build: ./containers/JunkSoup
    ports:
      - "2223:23" # Port 22 du container est exposé sur le port 2224 de la machine hôte
    container_name: junksoup
    tty: true
    stdin_open: true
    restart: always
    networks:
      - ctf

  weakssh:
    build: ./containers/weakSSH
    ports:
      - "2224:24" # Port 22 du container est exposé sur le port 2222 de la machine hôte
    container_name: weakssh
    tty: true
    stdin_open: true
    restart: always
    networks:
      - ctf

  dvwa:
    build: ./containers/DVWA
    ports:
      - "80:80"
    container_name: dvwa
    tty: true
    stdin_open: true
    restart: always
    networks:
      - ctf

networks:
  ctf:
    driver: bridge
